### ISSUE TITLE
app_lua: support for Fedora 35 with lua 5.4

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#2728]
```
which: no lua-config in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
which: no lua-config in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
CC (gcc) [M app_lua.so]         app_lua_api.o
app_lua_api.c: In function 'lua_sr_kemi_register_libs':
app_lua_api.c:1942:2: warning: implicit declaration of function 'luaL_openlib'; did you mean 'luaL_openlibs'? [-Wimplicit-f
unction-declaration]
 1942 |  luaL_openlib(L, "KSR", _sr_crt_KSRMethods, 0);
      |  ^~~~~~~~~~~~
      |  luaL_openlibs
CC (gcc) [M app_lua.so]         app_lua_kemi_export.o
CC (gcc) [M app_lua.so]         app_lua_mod.o
LD (gcc) [M app_lua.so]         app_lua.so
which: no lua-config in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
which: no lua-config in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
CC (gcc) [M app_lua_sr.so]              app_lua_sr_api.o
app_lua_sr_api.c: In function 'lua_sr_core_openlibs':
app_lua_sr_api.c:1614:2: warning: implicit declaration of function 'luaL_openlib'; did you mean 'luaL_openlibs'? [-Wimplici
t-function-declaration]
 1614 |  luaL_openlib(L, "sr",      _sr_core_Map, 0);
      |  ^~~~~~~~~~~~
      |  luaL_openlibs
CC (gcc) [M app_lua_sr.so]              app_lua_sr_exp.o
app_lua_sr_exp.c: In function 'lua_sr_exp_openlibs':
app_lua_sr_exp.c:3686:3: warning: implicit declaration of function 'luaL_openlib'; did you mean 'luaL_openlibs'? [-Wimplici
t-function-declaration]
 3686 |   luaL_openlib(L, "sr.sl",         _sr_sl_Map,          0);
      |   ^~~~~~~~~~~~
      |   luaL_openlibs
CC (gcc) [M app_lua_sr.so]              app_lua_sr_mod.o
LD (gcc) [M app_lua_sr.so]              app_lua_sr.so
```

**Comment by miconda** [comment]
Provide details of liblua-dev (or the equivalent name) package.

**Comment by sergey-safarov** [comment]
*Fedora 35*
```
[root@74700965220c /]# rpm -qa | grep lua
lua-libs-5.4.3-1.fc35.x86_64
lua-5.4.3-1.fc35.x86_64
lua-devel-5.4.3-1.fc35.x86_64
```

**Comment by miconda** [comment]
Isn't there lua 5.2 or 5.3? I do not think the modules support lua 5.4.

**Comment by sergey-safarov** [comment]
correct, no lua53 or lua52 or similar options.

**Comment by miconda** [comment]
Then you have to skip packaging these modules for the moment. Support for lua 5.4 is planned for the future, there is change in embedding api compared with the older versions, so it requires some development, even it could be a new module if the changes are very incompatible, like it happened with app_python2/3.

**Comment by sergey-safarov** [comment]
Now this a just warning.
But module compiled.
Think need to make sure the module is working.

**Comment by miconda** [comment]
Looking at the module Makefile, actually is expected to work with Lua 5.1 or 5.2, the other newer versions may need coding.

For Lua 5.3 it may be made working by defining `LUA_COMPAT_5_2`.

**Comment by miconda** [comment]
Should be implemented by the commit referenced above. In case of problems, open a new bug report.

**Comment by sergey-safarov** [comment]
Just tested the build on Fedora 36 with Lua 5.4.
Packages compiled successfully.
