### ISSUE TITLE
mi_xmlrpc compilation fails with GCC 6.2.0

### ISSUE THREAD

**Issue by gedia** [kamailio/kamailio#885]
Hello all,

Kamailio fails to build with GCC 6.2.0. It seems boolean constants TRUE and FALSE aren't recognised by the compiler. I'm getting multiple errors like the following:

```abyss_date.c: In function ‘DateToString’:
abyss_date.c:65:16: error: ‘FALSE’ undeclared (first use in this function)
         return FALSE;
                ^~~~~
```
[kamailio-4.4.4-build-log.txt](https://github.com/kamailio/kamailio/files/641616/kamailio-4.4.4-build-log.txt)

I'm attaching the complete build log.

**Comment by miconda** [comment]
Can you try to add to the file the changes introduced by the referenced commit above, or the diff at:

  * https://github.com/kamailio/kamailio/commit/1bba5faf5ced9fdd95446e4ae8913a0cf2426b85.diff

I guess that the problem is from the xmlrpc library no longer defining TRUE/FALSE.

Anyhow, if you start fresh, be aware that MI is deprecated and planned to be removed very soon (could happen even before next release). Start using the RPC interface, equivalent module being xmlprc. Or you can use jsonrpc-s.

**Comment by gedia** [comment]
Hello,

Thanks for the immediate reply. I applied the patch, and now I get fewer errors, but I still get some. I'm attaching the resulting build log.

I indeed have no dependence on MI, so I might as well exclude the module from being built altogether.
[kamailio-4.4.4-build-log-after-patch.txt](https://github.com/kamailio/kamailio/files/641732/kamailio-4.4.4-build-log-after-patch.txt)

**Comment by miconda** [comment]
You have to add same kind of patch in all the c files throwing that error. A better alternatives is to do it in a header and include it in the c files. But given that it is planned to be removed, any workaround solution would work to get it fixed for the moment.

**Comment by miconda** [comment]
I pushed a patch that maybe makes it working -- couldn't test it here. Reopen if other issues.
