### ISSUE TITLE
error on make cdp module

### ISSUE THREAD

**Issue by faratell** [kamailio/kamailio#3701]
Hello.
I have tried to install VoLTE Setup with Kamailio IMS on Ubuntu 22.04 form  https://open5gs.org/open5gs/docs/tutorial/02-VoLTE-setup/
 but I face two errors:
1) IPsec-tools packages not supported for Ubuntu 22.04.
2) when I tried to compile Kamailio the cdp modules were not compiled and showed this error:
make[2]: Entering directory '/usr/local/src/kamailio/src/modules/cdp'
Makefile.defs defs skipped
gcc -shared -Wl,-O2 -Wl,-E   -pthread -rdynamic -ldl -Wl,-Bsymbolic-functions acceptor.o acctstatemachine.o api_process.o authstatemachine.o cdp_functions.o cdp_load.o cdp_mod.o cdp_rpc.o cdp_stats.o common.o config.o configparser.o diameter_avp.o diameter_comm.o diameter_msg.o diameter_peer.o globals.o peer.o peermanager.o peerstatemachine.o receiver.o routing.o session.o tcp_accept.o timer.o transaction.o worker.o  -lxml2 -lrt -lpthread   -o cdp.so
/usr/bin/ld: cdp_mod.o:/usr/local/src/kamailio/src/modules/cdp/diameter_peer.h:68: multiple definition of `dp_first_pid'; acceptor.o:/usr/local/src/kamailio/src/modules/cdp/diameter_peer.h:68: first defined here
/usr/bin/ld: cdp_mod.o:/usr/local/src/kamailio/src/modules/cdp/diameter_peer.h:70: multiple definition of `pid_list'; acceptor.o:/usr/local/src/kamailio/src/modules/cdp/diameter_peer.h:70: first defined here
/usr/bin/ld: cdp_mod.o:/usr/local/src/kamailio/src/modules/cdp/diameter_peer.h:71: multiple definition of `pid_list_lock'; acceptor.o:/usr/local/src/kamailio/src/modules/cdp/diameter_peer.h:71: first defined here
/usr/bin/ld: diameter_peer.o:/usr/local/src/kamailio/src/modules/cdp/diameter_peer.h:68: multiple definition of `dp_first_pid'; acceptor.o:/usr/local/src/kamailio/src/modules/cdp/diameter_peer.h:68: first defined here
/usr/bin/ld: diameter_peer.o:/usr/local/src/kamailio/src/modules/cdp/diameter_peer.h:70: multiple definition of `pid_list'; acceptor.o:/usr/local/src/kamailio/src/modules/cdp/diameter_peer.h:70: first defined here
/usr/bin/ld: diameter_peer.o:/usr/local/src/kamailio/src/modules/cdp/diameter_peer.h:71: multiple definition of `pid_list_lock'; acceptor.o:/usr/local/src/kamailio/src/modules/cdp/diameter_peer.h:71: first defined here
/usr/bin/ld: receiver.o:/usr/local/src/kamailio/src/modules/cdp/diameter_peer.h:68: multiple definition of `dp_first_pid'; acceptor.o:/usr/local/src/kamailio/src/modules/cdp/diameter_peer.h:68: first defined here
/usr/bin/ld: receiver.o:/usr/local/src/kamailio/src/modules/cdp/diameter_peer.h:70: multiple definition of `pid_list'; acceptor.o:/usr/local/src/kamailio/src/modules/cdp/diameter_peer.h:70: first defined here
/usr/bin/ld: receiver.o:/usr/local/src/kamailio/src/modules/cdp/diameter_peer.h:71: multiple definition of `pid_list_lock'; acceptor.o:/usr/local/src/kamailio/src/modules/cdp/diameter_peer.h:71: first defined here
/usr/bin/ld: timer.o:/usr/local/src/kamailio/src/modules/cdp/diameter_peer.h:68: multiple definition of `dp_first_pid'; acceptor.o:/usr/local/src/kamailio/src/modules/cdp/diameter_peer.h:68: first defined here
/usr/bin/ld: timer.o:/usr/local/src/kamailio/src/modules/cdp/diameter_peer.h:70: multiple definition of `pid_list'; acceptor.o:/usr/local/src/kamailio/src/modules/cdp/diameter_peer.h:70: first defined here
/usr/bin/ld: timer.o:/usr/local/src/kamailio/src/modules/cdp/diameter_peer.h:71: multiple definition of `pid_list_lock'; acceptor.o:/usr/local/src/kamailio/src/modules/cdp/diameter_peer.h:71: first defined here
/usr/bin/ld: worker.o:/usr/local/src/kamailio/src/modules/cdp/diameter_peer.h:68: multiple definition of `dp_first_pid'; acceptor.o:/usr/local/src/kamailio/src/modules/cdp/diameter_peer.h:68: first defined here
/usr/bin/ld: worker.o:/usr/local/src/kamailio/src/modules/cdp/diameter_peer.h:70: multiple definition of `pid_list'; acceptor.o:/usr/local/src/kamailio/src/modules/cdp/diameter_peer.h:70: first defined here
/usr/bin/ld: worker.o:/usr/local/src/kamailio/src/modules/cdp/diameter_peer.h:71: multiple definition of `pid_list_lock'; acceptor.o:/usr/local/src/kamailio/src/modules/cdp/diameter_peer.h:71: first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [../../Makefile.rules:191: cdp.so] Error 1
make[2]: Leaving directory '/usr/local/src/kamailio/src/modules/cdp'
make[1]: *** [Makefile:511: modules] Error 1
make[1]: Leaving directory '/usr/local/src/kamailio/src'
make: *** [Makefile:34: all] Error 2

How can I solve it?

**Comment by henningw** [comment]
Hello, thanks for the report. Which Kamailio version are you using exactly?

**Comment by faratell** [comment]
I set "git checkout -b 5.3 origin/5.3". 
it is noticeable that no problem  when using ubuntu 18.04.

**Comment by henningw** [comment]
Hm, this is quite old and not maintained anymore. If you are also using the "https://github.com/herlesupreeth/kamailio" repository, you should probably address your question to this project. Please re-open if you can reproduce this with the current Kamailio git master or release branch 5.6/5.7 from this project repository.

**Comment by miconda** [comment]
For the records, cdp from devel branch compiles fine on ubuntu 22.04, I have just tried.

**Comment by faratell** [comment]
Thanks for your attention and replies.
I switched to branch 5.6 but the module jwt was not installed

jwt_mod.c:28:10: fatal error: jwt.h: No such file or directory
   28 | #include <jwt.h>
      |          ^~~~~~~
compilation terminated.
make[2]: *** [../../Makefile.rules:100: jwt_mod.o] Error 1
make[2]: Leaving directory '/usr/local/src/kamailio/src/modules/jwt'
make[1]: *** [Makefile:511: modules] Error 1
make[1]: Leaving directory '/usr/local/src/kamailio/src'
make: *** [Makefile:34: all] Error 2

**Comment by faratell** [comment]
Also in devel branch have error for ruby modul
app_ruby_api.h:26:10: fatal error: ruby.h: No such file or directory
   26 | #include <ruby.h>
      |          ^~~~~~~~
compilation terminated.
make[2]: *** [../../Makefile.rules:100: app_ruby_api.o] Error 1
make[2]: Leaving directory '/usr/local/src/kamailio-devel/kamailio/src/modules/app_ruby_proc'
make[1]: *** [Makefile:508: modules] Error 1
make[1]: Leaving directory '/usr/local/src/kamailio-devel/kamailio/src'
make: *** [Makefile:34: all] Error 2
