### ISSUE TITLE
ndb_redis: failed build on alpine

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#2325]
### Description

```
CC (gcc) [M db_redis.so]	db_redis_mod.o
CC (gcc) [M db_redis.so]	redis_connection.o
CC (gcc) [M db_redis.so]	redis_dbase.o
CC (gcc) [M db_redis.so]	redis_table.o
make[3]: 'libsrdb2.so.1.0' is up to date.
make[3]: 'libsrdb1.so.1.0' is up to date.
LD (gcc) [M db_redis.so]	db_redis.so
CC (gcc) [M ndb_redis.so]	ndb_redis_mod.o
CC (gcc) [M ndb_redis.so]	redis_client.o
redis_client.c: In function 'redisc_append_cmd':
redis_client.c:558:31: error: expected 'while' before ';' token
558 | STR_ZTOV(cmd->s[cmd->len], c);
| ^
redis_client.c: In function 'redisc_exec':
redis_client.c:949:33: error: expected 'while' before ';' token
949 | STR_ZTOV(cmd->s[cmd->len], c);
| ^
redis_client.c:983:34: error: expected 'while' before ';' token
983 | STR_ZTOV(cmd->s[cmd->len], c);
| ^
redis_client.c:988:31: error: expected 'while' before ';' token
988 | STR_ZTOV(cmd->s[cmd->len], c);
| ^
redis_client.c:1000:31: error: expected 'while' before ';' token
1000 | STR_ZTOV(cmd->s[cmd->len], c);
| ^
redis_client.c:1005:31: error: expected 'while' before ';' token
1005 | STR_ZTOV(cmd->s[cmd->len], c);
| ^
make[2]: *** [../../Makefile.rules:100: redis_client.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:511: modules] Error 1
make[1]: Leaving directory '/usr/src/kamailio/pkg/kamailio/alpine/src/kamailio-4d758d5258097760c09a762929c5893c14ac3eef/src'
make: *** [Makefile:34: all] Error 2
>>> ERROR: kamailio: build failed
>>> kamailio: Uninstalling dependencies...
(1/1) Purging .makedepends-kamailio (20200427.180718)
OK: 786 MiB in 178 packages
pre_build hook failed! (1)
```
Build failed after 4d758d5258097760c09a762929c5893c14ac3eef commit

**Comment by sergey-safarov** [comment]
fixed in commit 65ab73a7efabf4a55e913adfa604094c9ad88cdb
