### ISSUE TITLE
db_redis won't build with hiredis_cluster

### ISSUE THREAD

**Issue by srsrsr59** [kamailio/kamailio#4773]
db_redis won't build with redis cluster support.
Tried both towards latest release (6.1.3) and master branch.

```
 [9/9] RUN cd /tmp/src/modules/db_redis && export WITH_HIREDIS_CLUSTER && make Q=0:
0.250 config.mak included
0.420 make -wC ../.. cfg-defs
0.421 make[1]: Entering directory '/tmp/src'
0.422 normal Makefile.defs exec
0.452 target architecture <x86_64>, host architecture <x86_64>
0.482 making config...
0.489 make[1]: Leaving directory '/tmp/src'
0.491 config.mak included
0.577 make: --libs: No such file or directory
0.591 make: --libs: No such file or directory
0.635 config.mak included
0.725 make: --libs: No such file or directory
0.742 make: --libs: No such file or directory
0.780 gcc -fPIC -DPIC -g -pthread -funroll-loops -Wcast-align -m64 -minline-all-stringops -falign-loops -ftree-vectorize -fno-strict-overflow -mtune=generic -DKSR_PTHREAD_MUTEX_SHARED -Wall    -DNAME='"kamailio"' -DVERSION='"6.1.3"' -DARCH='"x86_64"' -DOS='linux_' -DOS_QUOTED='"linux"' -DCOMPILER='"gcc 14.2.0"' -D__CPU_x86_64 -D__OS_linux -DVERSIONVAL=6001003 -DCFG_DIR='"/usr/local/etc/kamailio/"' -DSHARE_DIR='"/usr/local/share/kamailio/"' -DRUN_DIR='"/var/run/kamailio/"' -DPKG_MALLOC -DSHM_MMAP -DDNS_IP_HACK -DUSE_MCAST -DUSE_TCP -DDISABLE_NAGLE -DHAVE_RESOLV_RES -DUSE_DNS_CACHE -DUSE_DNS_FAILOVER -DUSE_DST_BLOCKLIST -DUSE_NAPTR -DMEM_JOIN_FREE -DF_MALLOC -DQ_MALLOC -DTLSF_MALLOC -DDBG_SR_MEMORY -DUSE_TLS -DTLS_HOOKS -DUSE_CORE_STATS -DSTATISTICS -DMALLOC_STATS -DUSE_SCTP -DFAST_LOCK -DADAPTIVE_WAIT -DADAPTIVE_WAIT_LOOPS=1024 -DCC_GCC_LIKE_ASM -DHAVE_GETHOSTBYNAME2 -DHAVE_UNION_SEMUN -DHAVE_SCHED_YIELD -DHAVE_MSG_NOSIGNAL -DHAVE_MSGHDR_MSG_CONTROL -DHAVE_ALLOCA_H -DHAVE_TIMEGM -DHAVE_SCHED_SETSCHEDULER -DHAVE_IP_MREQN -DUSE_RAW_SOCKS -DHAVE_EPOLL -DHAVE_SIGIO_RT -DSIGINFO64_WORKAROUND -DUSE_FUTEX -DHAVE_SELECT  -I/usr/include/hiredis -D_FILE_OFFSET_BITS=64  -DWITH_SSL -DWITH_HIREDIS_CLUSTER -I/usr/local/include/hiredis_cluster -D_FILE_OFFSET_BITS=64  -DWITH_SSL -DMOD_NAME='"db_redis"' -DMOD_NAMEID='db_redis' -c db_redis_mod.c -o db_redis_mod.o -MMD -MP
0.870 In file included from redis_connection.h:29,
0.870                  from redis_table.h:29,
0.870                  from db_redis_mod.c:32:
0.870 /usr/local/include/hiredis_cluster/hircluster.h:50:27: error: expected identifier before numeric constant
0.870    50 | #define REDIS_ROLE_MASTER 1
0.870       |                           ^
0.870 redis_sentinels.h:48:9: note: in expansion of macro 'REDIS_ROLE_MASTER'
0.870    48 |         REDIS_ROLE_MASTER,
0.870       |         ^~~~~~~~~~~~~~~~~
0.880 make: *** [../../Makefile.rules:100: db_redis_mod.o] Error 1
```

**Comment by henningw** [comment]
Thanks for the report. Can you give more details about the used distribution and hiredis library version?

**Comment by srsrsr59** [comment]
Hi. used debian:trixie-slim (also tried with debian:trixie) .
latest hiredis-cluster, building it in the steps before
```
RUN git clone https://github.com/Nordix/hiredis-cluster.git /tmp-hiredis-cluster
RUN cd /tmp-hiredis-cluster && cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_SSL=ON -DDOWNLOAD_HIREDIS=ON && make && make install
```
(there's a buildoption DOWNLOAD_HIREDIS which toggles if it should use distros hiredis or download latest. Have tried both)

Can also add that I have also tried other kamailio tags down to 6.0.3 . None of them works. (but going below 6.1.x gives other errors).

**Comment by henningw** [comment]
It seems that you are building against hiredis-cluster git master. Please try a released version (e.g. this one https://github.com/Nordix/hiredis-cluster/releases/tag/0.15.0), maybe just an issue on their side.

**Comment by srsrsr59** [comment]
Hi. I'm pretty sure we also tested this earlier, but anyways - did it now (0.15.0) and getting the same result. 
Also tried the previous release, 0.14.0 - same result.

**Comment by henningw** [comment]
Thanks for the update. The sentinel support was added last year from @lbalaceanu - maybe he can comment on this issue, as it seems to be in this part of the code.

**Comment by jacky-w-j-li** [comment]
Same here with CMake builds. Had a quick look — the cluster check is in the Makefile but missing from `db_redis/CMakeLists.txt`. Ported that block over locally and it builds fine now.

**Comment by xkaraman** [comment]
@fsliwenjie Are you able to build with the latest `hiredis_cluster 0.15.0` successfully? with make and cmake?

Are you sure it picks it up? i am encountering the same build error for `db_redis` for both make and cmake as @srsrsr59.

```
CC (gcc) [M db_redis.so]                db_redis_mod.o
In file included from redis_connection.h:29,
                 from redis_table.h:29,
                 from db_redis_mod.c:32:
/usr/local/include/hiredis_cluster/hircluster.h:50:27: error: expected identifier before numeric constant
   50 | #define REDIS_ROLE_MASTER 1
      |                           ^
redis_sentinels.h:48:9: note: in expansion of macro ‘REDIS_ROLE_MASTER’
   48 |         REDIS_ROLE_MASTER,
```

which comes from due to cluster header which defines the same identifer as `redis_sentinel.h` from `db_redis` module.

**Comment by jacky-w-j-li** [comment]
@xkaraman It built through locally on an older hiredis_cluster, I only checked the CMake define was picked up for 0.15.0 and missed the sentinel symbol collision.

**Comment by xkaraman** [comment]
@fsliwenjie ΟΚ thanks for the update! although i think that symbol from hiredis_cluster was there for over 11 years! (https://github.com/Nordix/hiredis-cluster/blame/bcfdfc79efa5635cccc52e303d5b225072bb52db/hircluster.h). 

I am just trying to see if you got it somehow to build and with what versions of kamailio and hiredis_cluster you did. 

The collision should have started with kamailio 6.1 where the commit https://github.com/kamailio/kamailio/commit/8f4924708de5c3c533909d49e71a288ec57db3ef was introduced. did you maybe complie with a kamailio 6.0.x version?

**Comment by jacky-w-j-li** [comment]
@xkaraman No, 6.0.x builds fine with hiredis-cluster 0.15.0 (no sentinel code there). Only 6.1+/master hits the collision.

**Comment by srsrsr59** [comment]
So from what I read here it should build now. But I still can't get it to build with basic dockerfile.

```
FROM public.ecr.aws/debian/debian:trixie AS builder

WORKDIR /tmp

RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y \
  --no-install-recommends \
  build-essential \
  git \
  ssh \
  ca-certificates \
  bison \
  flex \
  make \
  pkg-config \
  libssl-dev \
  cmake \
  libhiredis-dev \
  libevent-dev

ENV PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

RUN git clone https://github.com/Nordix/hiredis-cluster.git /tmp-hiredis-cluster
RUN cd /tmp-hiredis-cluster && git checkout master
RUN cd /tmp-hiredis-cluster && cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_SSL=ON -DDOWNLOAD_HIREDIS=ON && make && make install

RUN git clone https://github.com/kamailio/kamailio.git /tmp
RUN cd /tmp && git checkout master

RUN cd /tmp/src/modules/db_redis && export WITH_HIREDIS_CLUSTER=1 && make CFLAGS="$CFLAGS -DWITH_REDIS_CLUSTER -fPIC"
```

Log/errormessage

```
docker build --no-cache .
[+] Building 49.5s (12/12) FINISHED                                                                                                                                                                                                       docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                0.0s
 => => transferring dockerfile: 951B                                                                                                                                                                                                                0.0s
 => [internal] load metadata for public.ecr.aws/debian/debian:trixie                                                                                                                                                                                1.2s
 => [internal] load .dockerignore                                                                                                                                                                                                                   0.0s
 => => transferring context: 2B                                                                                                                                                                                                                     0.0s
 => [1/9] FROM public.ecr.aws/debian/debian:trixie@sha256:50faf226e910f03b94b60ea871549a9b81af5708d18d5c1581bdf80147cfb89b                                                                                                                          0.0s
 => CACHED [2/9] WORKDIR /tmp                                                                                                                                                                                                                       0.0s
 => [3/9] RUN apt-get update &&   DEBIAN_FRONTEND=noninteractive apt-get install -y   --no-install-recommends   build-essential   git   ssh   ca-certificates   bison   flex   make   pkg-config   libssl-dev   cmake   libhiredis-dev   libevent  25.2s
 => [4/9] RUN git clone https://github.com/Nordix/hiredis-cluster.git /tmp-hiredis-cluster                                                                                                                                                          1.5s
 => [5/9] RUN cd /tmp-hiredis-cluster && git checkout master                                                                                                                                                                                        0.2s
 => [6/9] RUN cd /tmp-hiredis-cluster && cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_SSL=ON -DDOWNLOAD_HIREDIS=ON && make && make install                                                                                                      7.0s
 => [7/9] RUN git clone https://github.com/kamailio/kamailio.git /tmp                                                                                                                                                                              13.2s
 => [8/9] RUN cd /tmp && git checkout master                                                                                                                                                                                                        0.5s
 => ERROR [9/9] RUN cd /tmp/src/modules/db_redis && export WITH_HIREDIS_CLUSTER=1 && make CFLAGS="$CFLAGS -DWITH_REDIS_CLUSTER -fPIC"                                                                                                               0.6s
------
 > [9/9] RUN cd /tmp/src/modules/db_redis && export WITH_HIREDIS_CLUSTER=1 && make CFLAGS="$CFLAGS -DWITH_REDIS_CLUSTER -fPIC":
0.232 make -wC ../.. cfg-defs
0.233 make[1]: Entering directory '/tmp/src'
0.259 target architecture <x86_64>, host architecture <x86_64>
0.281 making config...
0.286 make[1]: Leaving directory '/tmp/src'
0.318 make: --libs: No such file or directory
0.331 make: --libs: No such file or directory
0.395 make: --libs: No such file or directory
0.408 make: --libs: No such file or directory
0.434 CC (gcc) [M db_redis.so]          db_redis_mod.o
0.528 CC (gcc) [M db_redis.so]          redis_connection.o
0.588 redis_connection.c: In function 'db_redis_connect':
0.588 redis_connection.c:314:37: error: passing argument 1 of 'db_redis_authenticate' from incompatible pointer type [-Wincompatible-pointer-types]
0.588   314 |         if(db_redis_authenticate(con->con, con->id->password) != 0) {
0.588       |                                  ~~~^~~~~
0.588       |                                     |
0.588       |                                     redisClusterContext *
0.588 In file included from redis_connection.c:27:
0.588 redis_sentinels.h:95:41: note: expected 'redisContext *' but argument is of type 'redisClusterContext *'
0.588    95 | int db_redis_authenticate(redisContext *ctx, const char *password);
0.588       |                           ~~~~~~~~~~~~~~^~~
0.589 redis_connection.c:426:27: error: passing argument 1 of 'redisClusterFree' from incompatible pointer type [-Wincompatible-pointer-types]
0.589   426 |                 redisFree(sentinel_ctx);
0.589       |                           ^~~~~~~~~~~~
0.589       |                           |
0.589       |                           redisContext *
0.589 In file included from redis_connection.h:29,
0.589                  from redis_connection.c:26:
0.589 /usr/local/include/hiredis_cluster/hircluster.h:196:44: note: expected 'redisClusterContext *' but argument is of type 'redisContext *'
0.589   196 | void redisClusterFree(redisClusterContext *cc);
0.589       |                       ~~~~~~~~~~~~~~~~~~~~~^~
0.618 make: *** [../../Makefile.rules:100: redis_connection.o] Error 1
```

Tried both against latest hiredis-cluster release and master.

This time I actually got AI to make a patch that gets it to build. But I don't have a clue if what it fixes makes sense...
```
--- a/src/modules/db_redis/redis_connection.c
+++ b/src/modules/db_redis/redis_connection.c
@@ -311,9 +311,11 @@ int db_redis_connect(km_redis_con_t *con)
 #endif
 #endif
 	// Authenticate if needed
+#ifndef WITH_HIREDIS_CLUSTER
 	if(db_redis_authenticate(con->con, con->id->password) != 0) {
 		LM_ERR("Authentication error\n");
 		goto err;
 	}
+#endif
 #ifndef WITH_HIREDIS_CLUSTER
 	reply = redisCommand(con->con, "PING");
@@ -418,8 +420,10 @@ err:
 	if(con->con) {
 		redisFree(con->con);
 		con->con = NULL;
 	}
+#ifndef WITH_HIREDIS_CLUSTER
 	if(sentinel_ctx)
 		redisFree(sentinel_ctx);
+#endif
 	return -1;
 }
--- a/src/modules/db_redis/redis_dbase.c
+++ b/src/modules/db_redis/redis_dbase.c
@@ -2714,7 +2714,7 @@ static int db_redis_perform_update(const db1_con_t *_h, km_redis_con_t *con,
 				if(db_redis_key_add_str(&query_v, &type_key->key) != 0) {
 					LM_ERR("Failed to add key to delete query\n");
 					goto error;
 				}
-				if(db_redis_key_add_str(&query_v, key) != 0) {
+				if(db_redis_key_add_str(&query_v, &key->key) != 0) {
 					LM_ERR("Failed to add key to delete query\n");
 					goto error;
 				}
--- a/src/modules/db_redis/redis_sentinels.c
+++ b/src/modules/db_redis/redis_sentinels.c
@@ -185,6 +185,7 @@ static redisReply *replica_list_pop(struct reply_list *list, size_t idx)
 
 
+#ifndef WITH_HIREDIS_CLUSTER
 static int validate_role(
 		km_redis_con_t *con, const char *host, int port, redis_role_t role)
 {
@@ -533,3 +534,4 @@ err:
 		freeReplyObject(reply);
 	return -1;
 }
+#endif /* WITH_HIREDIS_CLUSTER */
```

**Comment by lbalaceanu** [comment]
Hi,

Sorry for joining the discussion so late, I am also looking on this issue now.

**Comment by lbalaceanu** [comment]
Hello,

Just a quick note that I am working on reshuffling the sentinel code so that building with cluster or sentinel will work fine and also the code stays relatively easy to read. I am bringing my changes here: https://github.com/lbalaceanu/kamailio/commit/0b16043b470ffc1242dcee84c4a5c89c0f0f900b.

The code is yet untested and it might conflict with @xkaraman's code somehow, but I will look more on this when I come back on Tuesday (Monday is free day here).

Sorry for the inconvenience with this cluster build.

**Comment by henningw** [comment]
@lbalaceanu Thank you for looking into it. I think we are getting close. I tried to build it, applied your patch on top of current git master, and I just get one last warning (with WITH_REDIS_CLUSTER ?= 1, WITH_SENTINELS ?= 0):

```
gcc -fPIC -DPIC -g -pthread -funroll-loops -Wcast-align -m64 -minline-all-stringops -falign-loops -ftree-vectorize -fno-strict-overflow -mtune=generic -DKSR_PTHREAD_MUTEX_SHARED -Wall    -DNAME='"kamailio"' -DVERSION='"6.2.0-dev1"' -DARCH='"x86_64"' -DOS='linux_' -DOS_QUOTED='"linux"' -DCOMPILER='"gcc 13.3.0"' -D__CPU_x86_64 -D__OS_linux -DVERSIONVAL=6002000 -DCFG_DIR='"/usr/local/etc/kamailio/"' -DSHARE_DIR='"/usr/local/share/kamailio/"' -DRUN_DIR='"/var/run/kamailio/"' -DPKG_MALLOC -DSHM_MMAP -DDNS_IP_HACK -DUSE_MCAST -DUSE_TCP -DDISABLE_NAGLE -DHAVE_RESOLV_RES -DUSE_DNS_CACHE -DUSE_DNS_FAILOVER -DUSE_DST_BLOCKLIST -DUSE_NAPTR -DMEM_JOIN_FREE -DF_MALLOC -DQ_MALLOC -DTLSF_MALLOC -DDBG_SR_MEMORY -DUSE_TLS -DTLS_HOOKS -DUSE_CORE_STATS -DSTATISTICS -DMALLOC_STATS -DUSE_SCTP -DFAST_LOCK -DADAPTIVE_WAIT -DADAPTIVE_WAIT_LOOPS=1024 -DCC_GCC_LIKE_ASM -DHAVE_GETHOSTBYNAME2 -DHAVE_UNION_SEMUN -DHAVE_SCHED_YIELD -DHAVE_MSG_NOSIGNAL -DHAVE_MSGHDR_MSG_CONTROL -DHAVE_ALLOCA_H -DHAVE_TIMEGM -DHAVE_SCHED_SETSCHEDULER -DHAVE_IP_MREQN -DUSE_RAW_SOCKS -DHAVE_EPOLL -DHAVE_SIGIO_RT -DSIGINFO64_WORKAROUND -DUSE_FUTEX -DHAVE_SELECT  -I/usr/include/hiredis -D_FILE_OFFSET_BITS=64  -DWITH_SSL -DWITH_HIREDIS_CLUSTER -I/usr/local/include/hiredis_cluster -D_FILE_OFFSET_BITS=64  -DWITH_SSL -DMOD_NAME='"db_redis"' -DMOD_NAMEID='db_redis' -c redis_dbase.c -o redis_dbase.o -MMD -MP
redis_dbase.c: In function ‘db_redis_perform_update’:
redis_dbase.c:2717:67: warning: passing argument 2 of ‘db_redis_key_add_str’ from incompatible pointer type [-Wincompatible-pointer-types]
 2717 |                                 if(db_redis_key_add_str(&query_v, key) != 0) {
      |                                                                   ^~~
      |                                                                   |
      |                                                                   redis_key_t * {aka struct redis_key *}
In file included from redis_dbase.c:32:
redis_table.h:65:57: note: expected ‘const str *’ {aka ‘const struct _str *’} but argument is of type ‘redis_key_t *’ {aka ‘struct redis_key *’}
   65 | int db_redis_key_add_str(redis_key_t **list, const str *entry);
      |                                              ~~~~~~~~~~~^~~~~
```

The other modes works fine for me.

**Comment by lbalaceanu** [comment]
Hi @henningw,

I am back from an unplanned period of days off.

I just pushed a fix for that warning you mention although I am not savvy in the cluster code involved. 

I still have to test my own code, which means I have to adapt some internal code.

**Comment by henningw** [comment]
> I am back from an unplanned period of days off.
> I just pushed a fix for that warning you mention although I am not savvy in the cluster code involved.
> I still have to test my own code, which means I have to adapt some internal code.

Thank you. I have tested https://github.com/lbalaceanu/kamailio/commit/817a5867d7d3d4d5 - this fixes the error for me. Tested the build with and without Cluster and with Sentinel.

Let me know how it goes for the test. You can also just create a PR with the changes from your tree and then also other people could test.

**Comment by lbalaceanu** [comment]
I created this PR https://github.com/kamailio/kamailio/pull/4912.

**Comment by henningw** [comment]
The PR was merged, it should work now. The sentinel is the default, cluster needs to be explicitly enabled in the build scripts. Close this issue. If you are still seeing problems, please re-open.
