### ISSUE TITLE
xhttp_prom: module no longer builds on branch 5.8

### ISSUE THREAD

**Issue by lbalaceanu** [kamailio/kamailio#4521]
### Description

Trying to build Kamailio with `make all` fails in module xhttp_prom after commit 7a3326c9d0663eb44a912b39065f60783b475697.

#### Reproduction

Try to build xhttp_prom.

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
/xhttp_prom$ make
CC (gcc) [M xhttp_prom.so]		prom.o
prom.c: In function ‘metric_generate’:
prom.c:198:40: error: ‘xhttp_prom_tags_braces’ undeclared (first use in this function)
  198 |         if(prom_body_printf(ctx, "%s", xhttp_prom_tags_braces) == -1) {
      |                                        ^~~~~~~~~~~~~~~~~~~~~~
prom.c:198:40: note: each undeclared identifier is reported only once for each function it appears in
make: *** [../../Makefile.rules:100: prom.o] Error 1

```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
kamailio 5.8.6
```

* **Operating System**:

```
Ubuntu
```

**Comment by henningw** [comment]
Thanks, reverted by 1daebf7d1d8
